### ISSUE TITLE
Maps not really uploading to the device on windows

### ISSUE THREAD

**Issue by Ebe66** [vti/elemntary#1]
For me at least on windows 11 the map upload function is not working correctly.
After hitting the upload button it takes about half a second for the "Map successfully uploaded" message to appear. Map files are unpacked to the tmp directory. But when checking after restarting on the device the map files are not updated (timestamp)
After manually deleting the maps on the device and restarting and retrying the upload the same successful message is displayed but no files are to be found in the maps folder.

**Comment by Ebe66** [comment]
[elemntary.log](https://github.com/vti/elemntary/files/9591382/elemntary.log)

The requested log. Have not get any further then starting the app and getting the adb error for some reason

**Comment by Ebe66** [comment]
[elemntary.log](https://github.com/vti/elemntary/files/9591404/elemntary.log)
New log and maybe I know what's going wrong. The log shows push' 'c:\Windows-Wahoo-Map-Creator-Osmosis\elemntary301/tmp/netherlands' '/sdcard/maps/tiles/8/ but the tmp folder does not contain a folder netherlands it directly contains the tile structure. It might be my version of the zip packed maps differs from what Benjamin is doing atm. He based his work on my and Henks work, but I still use my own version to generate maps not Benjamins (treee111)

**Comment by vti** [comment]
Should be fixed in [v0.4.0](https://github.com/vti/elemntary/releases/tag/v0.4.0).
