### ISSUE TITLE
Copy device theme to Elemnt

### ISSUE THREAD

**Issue by masc4ii** [vti/elemntary#3]
Currently we're able to copy map data to the Wahoo device. Fantastic!
 
In the last day I created my custom rendering theme with new icons and new xml. I copy it manually all the time and reset cache with your tool.
Do you think it is possible to create a new function to your app, copying these rendering theme files to the Wahoo, in the same way as you do it with map data? This would make the process even better.

I am talking about these files and subfolder: https://github.com/treee111/wahooMapsCreator/tree/develop/device_themes/vtm_theme_poi

**Comment by vti** [comment]
@masc4ii sure, it should be possible. So this should be a separate section similar to "upload map" where you choose the files?

**Comment by masc4ii** [comment]
Great! Yes, for example. 😄

**Comment by vti** [comment]
@masc4ii if you can run from sources, check this branch feature/theme-upload.

**Comment by masc4ii** [comment]
@vti Oh yes... great. That works fine on BigSur, and is exactly what I was looking for. Thank you so much. If you want me to compile macOS releases for BigSur+ Intel, let me know please!

**Comment by vti** [comment]
@masc4ii you're welcome. The macos binaries are built automatically, or they are not working for you?

**Comment by masc4ii** [comment]
Oh nice... last time when I was looking for, I didn't find any release for macOS, so I started compiling for myself. In a quick test v0.4.3 was starting up. (Don't have the Wahoo here now.)

**Comment by vti** [comment]
Included in v0.5.0. Enjoy!
