### ISSUE TITLE
Warning/error after selecting directory not containing maps

### ISSUE THREAD

**Issue by Ebe66** [vti/elemntary#4]
When uploading maps to the device, if you accidentally select a folder not containing map tiles you get a warning/error that no map tiles were found (good). But if you, after that, select a folder that does contain map tiles the warning/error message does not disappear.
The subsequent upload however does find the tiles and uploads them just fine.

**Comment by vti** [comment]
Fixed in 9c4abc3be3b065ad2cddc3bcc014d107a3b7fbd7
