### ISSUE TITLE
Device Not Authorized

### ISSUE THREAD

**Issue by s3dbw** [vti/elemntary#7]
When I try and connect using Elemntary, I can see the device through file explorer, but Elemntry under devices says "Unknown 47223710409 not authorized" Am I missing something in the setup or are there other install files I need? Thanks

**Comment by vti** [comment]
@s3dbw yes, follow the instructions for your device. You need to hold specific buttons based on the model and then you can refresh. It can be a bit tricky, so try couple times.

**Comment by s3dbw** [comment]
Thanks for getting back Its a Roam 2, is the same as the Bolt V2, or do I follow instructions for BoltV1 and Roam?

**Comment by vti** [comment]
@s3dbw

```
BOLT v2 and ROAM v2
press the power, up and down buttons at the same time (this could be a bit tricky)
```

**Comment by s3dbw** [comment]
Cheers, will give it a go

**Comment by s3dbw** [comment]
It is tricky, but got it third time of asking, many thanks

**Comment by vti** [comment]
@s3dbw  maybe we can close the issue then? :)

**Comment by s3dbw** [comment]
Agreed and thanks again
