### ISSUE TITLE
Language not selected by default 

### ISSUE THREAD

**Issue by pdelteil** [vti/elemntary#8]
I got this error (TypeError: Cannot read properties of undefined (reading 'menu')) 
![image](https://user-images.githubusercontent.com/20244863/235584666-cd7d8549-1646-40e8-898d-8afeb2a366b3.png)

This is the start window

<img src="https://user-images.githubusercontent.com/20244863/235584951-6277aacd-95c8-4441-b2f8-d6782b90b0e3.png" width="60%" >

Labels not shown:

<img src="https://user-images.githubusercontent.com/20244863/235584986-0d627a66-d779-4029-b140-377f0fdd03e1.png" width="50%" >

**Fixed selecting "English"  in Language menu.  Or setting `{"locale":"en"}` in `~/.config/elemntary/settings.json`**

**Comment by vti** [comment]
@pdelteil  thanks for reporting! What language do you have set by default? I guess there is a bug that unknown language is not properly handled.

**Comment by pdelteil** [comment]
Hello,

Language is en-US as shown here:

![Screenshot from 2023-05-02 01-13-39](https://user-images.githubusercontent.com/20244863/235592581-a78ac7cf-edca-48d5-a8c3-6ac76bb4464f.png)

**Comment by vti** [comment]
Fixed in 5dac565f70589687025096469fbb768a566821ff. Release is on its way.

**Comment by vti** [comment]
Part of v0.5.5 release.
